name: mc server test and then build&push the image to DockeHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04
    name: server-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: remove old jdk
        run: |
          sudo rm -rf /usr/lib/jvm/*

      - name: Setup JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless

      - name: Test jdk
        run: java -version

      - name: Copy config files
        run: cp -r ./configs/* ./server/

      - name: run server
        run: |
          cd server
          sudo timeout -s SIGKILL 100 bash start.sh
          EXIT_CODE=$?
          if [ $EXIT_CODE -eq 124 ]; then
            echo "Script timed out, but it's considered a success."
            exit 0
          else
            echo "Script failed with exit code $EXIT_CODE."
            exit $EXIT_CODE

#      - name: Login in Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#
#      - name: Push to Dockerhub
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/action:latest