name: mc server test and then build&push the image to DockerHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04
    name: server-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          load-mode: strict

      - name: remove old jdk
        run: |
          sudo rm -rf /usr/lib/jvm/*

      - name: Setup JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.JAVA_VERSION }}

#      - name: Setup screen
#        run: sudo apt-get install -y screen

      - name: Test jdk
        run: java -version

      - name: Copy config files
        run: cp -r ./configs/* ./server/

      - name: run server
        run: |
          sudo chmod +x server/start.sh
          sudo chmod +x ./test_server.sh
          cd server
          nohup ./start.sh > output.log 2>&1 &
          cd -

      - name: test server
        run: |
          ss -tnlp
          ps aux | grep fabric-server-launch
          sudo bash test_server.sh

      - name: Login in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          build-args: |
            JAVA_VERSION=${{ env.JAVA_VERSION }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mc-server:${{ env.SERVER_VERSION }}-${{ github.run_number }}

      - name: Update mc-server.yaml with new image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mc-server:${{ env.SERVER_VERSION }}-${{ github.run_number }}
          sed -i "s|image: .*|image: ${IMAGE_NAME}|g" ./deployment/mc-server.yaml

      - name: Chetout to commit and push
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/mc-server:${{ env.SERVER_VERSION }}-${{ github.run_number }}
          git config --local user.email "suzcuser@github.com"
          git config --local user.name "GitHub Action"
          git add ./deployment/mc-server.yaml
          git commit -m "Update image to ${IMAGE_NAME}"
          git push origin update-deployment