name: mc server test and then build&push the image to DockeHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04
    name: server-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: remove old jdk
        run: |
          sudo rm -rf /usr/lib/jvm/*

      - name: Setup JDK
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless

#      - name: Setup screen
#        run: sudo apt-get install -y screen

      - name: Test jdk
        run: java -version

      - name: Copy config files
        run: cp -r ./configs/* ./server/

      - name: run server
        run: |
          sudo chmod +x ./start.sh
          sudo chmod +x ./test_server.sh
          nohup ./start.sh > output.log 2>&1 &
          ./test_server.sh
#          screen -dmS server ./start.sh
#          screen -ls
#          sleep 100
#          screen -S server -p 0 -X stuff "stop$(printf \\r)"

#      - name: Login in Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#
#      - name: Push to Dockerhub
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/action:latest