name: mc server test and then build&push the image to DockeHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: server-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        run: |
          sudo su
          apt-get update
          apt-get install -y openjdk-17-jre-headless

      - name: Test jdk
        run: java -version

      - name: Copy config files
        run: cp -r ./configs/* ./server/

      - name: run server
        run: |
          cd server
          ./start.sh


#      - name: Login in Dockerhub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_TOKEN }}
#
#      - name: Push to Dockerhub
#        uses: docker/build-push-action@v5
#        with:
#          push: true
#          tags: ${{ secrets.DOCKER_USERNAME }}/action:latest