name: mc server test and then build&push the image to DockeHub
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-22.04
    name: server-test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: remove old jdk
        run: |
          sudo rm -rf /usr/lib/jvm/*

      - name: Setup JDK
        run: |
          source vars
          sudo apt-get update
          sudo apt-get install -y ${java_version}

#      - name: Setup screen
#        run: sudo apt-get install -y screen

      - name: Test jdk
        run: java -version

      - name: Copy config files
        run: cp -r ./configs/* ./server/

      - name: pwd&&ll
        run: |
          pwd
          ls -l

      - name: run server
        run: |
          sudo chmod +x server/start.sh
          sudo chmod +x ./test_server.sh
          cd server
          nohup ./start.sh > output.log 2>&1 &
          cd -

      - name: test server
        run: |    
          ss -tnlp
          ps aux | grep fabric-server-launch
          sudo bash test_server.sh

      - name: Login in Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Dockerhub
        uses: docker/build-push-action@v6
        vars:
          java_version: ${{ vars.java_version }}
          server_version: ${{ vars.server_version }}
        with:
          build-args:
            JAVA_VERSION=${java_version}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mc-server:${server_version}-${{ github.sha }}